name: newsee
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  awesome_notifications: ^0.10.1
  biometric_signature: ^6.2.0
  bloc: ^9.0.0
  camera: ^0.11.1
  connectivity_plus: ^6.1.4
  crypto: ^3.0.3
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  dropdown_search: ^5.0.6
  encrypt: ^5.0.3
  english_words: ^4.0.0
  equatable: ^2.0.5
  file_picker: ^10.1.2
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_chat_core: ^2.9.0
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^2.11.0
  flutter_dotenv: ^6.0.0
  flutter_image_compress: ^2.4.0
  flutter_pdfview: 1.3.2
  flutter_slidable: ^3.1.0
  flutter_svg: ^2.0.10+1
  flyer_chat_audio_message: ^0.0.12+2
  flyer_chat_image_message: ^2.2.2
  flyer_chat_text_message: ^2.5.1
  geocoding: ^4.0.0
  geolocator: ^14.0.0
  get_it: ^8.0.0
  go_router: ^14.3.0
  google_maps_flutter: ^2.12.3
  google_ml_kit: ^0.20.0
  image: ^4.5.4
  image_cropper: ^9.1.0
  image_picker: ^1.1.2
  insta_image_viewer: ^1.0.4
  internet_connection_checker: ^3.0.1
  json_annotation: ^4.9.0
  keyboard_detection: ^0.8.0
  kyc_verification:
    path: D:\FlutterApps\newsee\Kyc_Verification
  loading_animation_widget: ^1.3.0
  local_auth: ^2.3.0
  local_auth_android: ^1.0.49
  mobile_scanner: ^7.0.1
  number_paginator: ^1.1.0
  package_info_plus: ^8.0.0
  path: ^1.9.1
  path_provider: ^2.1.2
  pdfx: ^2.6.0
  percent_indicator: ^4.2.2
  permission_handler: ^11.3.1
  pin_code_fields: ^8.0.1
  popover: ^0.3.1
  pretty_dio_logger: ^1.4.0
  provider: ^6.1.2
  reactive_forms: ^18.0.0
  share_plus: ^10.1.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  socket_io_client: ^3.0.0
  sqflite: ^2.4.2
  tflite_flutter: ^0.11.0
  url_launcher: ^6.3.1
  video_player: ^2.10.1
  webview_flutter: ^4.7.0
  xml2json: ^6.2.7

dev_dependencies:
  build_runner: ^2.4.13
  pointycastle: 3.7.3

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for in
  #ation about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/logo.jpg
    - assets/logo1.jpg
    - assets/whatsapp.svg
    - assets/Agri_Loan.svg
    - assets/app_background_1.svg
    - assets/app_background_2.svg
    - assets/Gold_Loan.svg
    - assets/Home_Loan.svg
    - assets/MSME.svg
    - assets/Vehicle_Loan.svg
    - assets/Retail_loan.svg
    - assets/data/cif.json
    - assets/data/dedupe.json
    - assets/data/aadhaar_response.json
    - assets/data/lov.json
    - assets/data/product.json
    - assets/data/productschema.json
    - assets/data/statecity.json
    - assets/data/citylist.json
    - assets/data/districtlist.json
    - assets/data/documents.json
    - assets/data/cifdata.json
    - assets/data/cibil.json
    - assets/data/crop.json
    - assets/data/get_crop.json
    - assets/data/RBIH_LAND_CROP_RESP.json
    - assets/ml_models/
    - assets/data/otpvalidation.json
    - assets/data/aadhaarvalidation.json
    - assets/images/logo.png
    # - assets/certificates/myserver.cer
    # - assets/logo1.jpg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
